### PR TITLE
fix #4: support G15 5520 model

### LINKED ISSUE #3: Power and fan management does not work on custom bash prompts
If the bash prompt does not end with '$' or '#', the app waits for the child bash process to print these values to stdout until timeout, and fan and power related functions do not work as a result. The current workaround is to have an unmodified bash prompt, but this is not optimal. It would be better to detect the current bash prompt and wait for it instead.

### LINKED ISSUE #4: G15 5520 compatibility
Hello! I have a Dell G15 5520, and would want to add it as compatible, to add at least G button function and put the fans to the max. How can I intercept AWCC ACPI commands from windows? I tried extracting DSDT, and reading ACPI tables, but couldn't compile it to even try to locate some functions.

### LINKED ISSUE #5: Program shell commands keep spilling into .bash_history
Self explanatory. Root user bash_history gets flushed with ACPI commands.

### PR DESCRIPTION
**Pull request by poly000**
-----------------------------------
close #3, close #5

### CODE REVIEW

**Comment by cemkaya-mpi** [comment]
Hello,

If USTT_Fullspeed does not work on the G15 5515, could you also set the `power_modes_dict` accordingly on the G15 5515? I will accept the merge request afterward. Appreciate the contribution!

Also, does the 5515 model not have a rgb keyboard? For the 5525 It was optional on the dell website. In any case, it would be good to have a settings button to enable/disable the keyboard backlight or power control in case it does not work for you.

**Comment by poly000** [comment]
Hello, checked DELL official site, full RGB zone is optional for both 5515 and 5520.
I will try find USTT_Fullspeed call for 5520, but I don't have a g15 5515 laptop, thus I cannot help

**Comment by cemkaya-mpi** [comment]
Oh sorry, I misread the model you have. Actually, the power modes should be the same as you see on AWCC. In case there is no USTT_Fullspeed for the 5520, we can just define the dictionary without it, and it will not be shown in the GUI. The power modes range from 0xa0 to 0xab, but not all are supported on all models. When someone with a 5515 opens an issue, support for that model can also be added.

Thanks again for the contributions! Let me know if you want a more active role in the project. It is pretty much on maintenance mode atm since I do not have enough time for this project.

**Comment by poly000** [comment]
> Oh sorry, I misread the model you have. Actually, the power modes should be the same as you see on AWCC. In case there is no USTT_Fullspeed for the 5520, we can just define the dictionary without it, and it will not be shown in the GUI. The power modes range from 0xa0 to 0xab, but not all are supported on all models. When someone with a 5515 opens an issue, support for that model can also be added.
> 
> Thanks again for the contributions! Let me know if you want a more active role in the project. It is pretty much on maintenance mode atm since I do not have enough time for this project.

> for i in {0..9} {a..b} ; do echo "\_SB.AMWW.WMAX 0 0x15 {0x01, 0xa${i}, 0x00, 0x00}" | sudo dd of=/proc/acpi/call 2> /dev/null ; sudo cat /proc/acpi/call ; echo \ for 0xa{$i}; done
0x0 for 0xa{0}
0x0 for 0xa{1}
0xffffffff for 0xa{2}
0x0 for 0xa{3}
0xffffffff for 0xa{4}
0x0 for 0xa{5}
0xffffffff for 0xa{6}
0xffffffff for 0xa{7}
0xffffffff for 0xa{8}
0xffffffff for 0xa{9}
0xffffffff for 0xa{a}
0x0 for 0xa{b}

Here are my results
I am not familar with Qt, but as I am still using my Dell G15 laptop I may work on this project, although mainly for my personal use

**Comment by poly000** [comment]
> Oh sorry, I misread the model you have. Actually, the power modes should be the same as you see on AWCC. In case there is no USTT_Fullspeed for the 5520, we can just define the dictionary without it, and it will not be shown in the GUI. The power modes range from 0xa0 to 0xab, but not all are supported on all models. When someone with a 5515 opens an issue, support for that model can also be added.
> 
> Thanks again for the contributions! Let me know if you want a more active role in the project. It is pretty much on maintenance mode atm since I do not have enough time for this project.

I guess we could add some patch after detected laptop model by append a list of lambdas editing
because almost all codes are same between models

**Comment by Alastor-Ripley** [comment]
I actually have the Dell G15 5515, running Garuda-Linux Hyprland edition, if I may be of assistance.

**Comment by poly000** [comment]
> I actually have the Dell G15 5515, running Garuda-Linux Hyprland edition, if I may be of assistance.

Hi! thanks for your willing to help. Could you check [DSDT](https://wiki.archlinux.org/title/DSDT) on archwiki ahd dump a copy of it?

**Comment by Alastor-Ripley** [comment]
> > I actually have the Dell G15 5515, running Garuda-Linux Hyprland edition, if I may be of assistance.
> 
> Hi! thanks for your help. Could you check [DSDT](https://wiki.archlinux.org/title/DSDT) on archwiki ahd dump a copy of it?
> We guess almost all modes have same value bwtween models, the major difference will be the ACPI call prefix

Do you need dsdt.dsl or dsdt.dat, or something  else, and would I just paste the contents here or upload the file on like google drive and share the link?

**Comment by cemkaya-mpi** [comment]
Could you open an issue for your laptop model with the dsdt ?

**Pull request merged**
